import {
  TrendingUp, Percent, PieChart, DollarSign, Calculator, Target,
  Heart, Activity, Zap, Moon, Utensils, Droplets,
  PlusSquare, Square, Sigma, Lightbulb, Infinity, Dice6,
  Coffee, Scissors, Globe, Banknote, Fuel,
  Home, BarChart3, Layers, Sparkles, Box, Lock, Type, Palette,
} from 'lucide-react'

export type Category = 'finance' | 'health' | 'math' | 'tools'

export interface Calculator {
  id: string
  name: string
  description: string
  category: Category
  icon: React.ElementType
  href: string
  color: string
}

export const CALCULATORS: Calculator[] = [
  // Finance - 25 Calculators (all have pages)
  {
    id: 'compound-interest',
    name: 'Compound Interest',
    description: 'Calculate compound interest over time',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/compound-interest',
    color: '#1f6feb',
  },
  {
    id: 'loan-payment',
    name: 'Loan Calculator',
    description: 'Calculate monthly loan payments',
    category: 'finance',
    icon: DollarSign,
    href: '/finance/loan',
    color: '#1f6feb',
  },
  {
    id: 'vat-calculator',
    name: 'VAT Calculator',
    description: 'Calculate VAT/Sales Tax',
    category: 'finance',
    icon: Percent,
    href: '/finance/vat',
    color: '#1f6feb',
  },
  {
    id: 'profit-margin',
    name: 'Profit Margin',
    description: 'Calculate profit margins',
    category: 'finance',
    icon: PieChart,
    href: '/finance/profit',
    color: '#1f6feb',
  },
  {
    id: 'salary-converter',
    name: 'Salary Converter',
    description: 'Convert between salary periods',
    category: 'finance',
    icon: Calculator,
    href: '/finance/salary',
    color: '#1f6feb',
  },
  {
    id: 'retirement',
    name: 'Retirement Calculator',
    description: 'Plan your retirement savings',
    category: 'finance',
    icon: Target,
    href: '/finance/retirement',
    color: '#1f6feb',
  },
  {
    id: 'breakeven',
    name: 'Break Even',
    description: 'Find your break-even point',
    category: 'finance',
    icon: Lightbulb,
    href: '/finance/breakeven',
    color: '#1f6feb',
  },
  {
    id: 'mortgage',
    name: 'Mortgage Calculator',
    description: 'Calculate mortgage payments',
    category: 'finance',
    icon: Home,
    href: '/finance/mortgage',
    color: '#1f6feb',
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    description: 'Track and analyze spending',
    category: 'finance',
    icon: PieChart,
    href: '/finance/expense-tracker',
    color: '#1f6feb',
  },
  {
    id: 'amortization',
    name: 'Amortization Schedule',
    description: 'Generate loan amortization schedule',
    category: 'finance',
    icon: BarChart3,
    href: '/finance/amortization',
    color: '#1f6feb',
  },
  {
    id: 'debt-payoff',
    name: 'Debt Payoff Calculator',
    description: 'Calculate time to pay off debt',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/debt-payoff',
    color: '#1f6feb',
  },
  {
    id: 'roi',
    name: 'ROI Calculator',
    description: 'Calculate return on investment',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/roi',
    color: '#1f6feb',
  },
  {
    id: 'simple-interest',
    name: 'Simple Interest Calculator',
    description: 'Calculate simple interest',
    category: 'finance',
    icon: Percent,
    href: '/finance/simple-interest',
    color: '#1f6feb',
  },
  {
    id: 'tax-calculator',
    name: 'Tax Calculator',
    description: 'Calculate income tax',
    category: 'finance',
    icon: Calculator,
    href: '/finance/tax',
    color: '#1f6feb',
  },
  {
    id: 'investment',
    name: 'Investment Calculator',
    description: 'Plan your investments',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/investment',
    color: '#1f6feb',
  },
  {
    id: 'net-worth',
    name: 'Net Worth Calculator',
    description: 'Calculate your net worth',
    category: 'finance',
    icon: BarChart3,
    href: '/finance/net-worth',
    color: '#1f6feb',
  },
  {
    id: 'apr-to-apy',
    name: 'APR to APY Converter',
    description: 'Convert APR to APY',
    category: 'finance',
    icon: Percent,
    href: '/finance/apr-to-apy',
    color: '#1f6feb',
  },
  {
    id: 'dividend',
    name: 'Dividend Calculator',
    description: 'Calculate dividend income',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/dividend',
    color: '#1f6feb',
  },
  {
    id: 'credit-card-payoff',
    name: 'Credit Card Payoff',
    description: 'Plan credit card debt payoff',
    category: 'finance',
    icon: DollarSign,
    href: '/finance/credit-card-payoff',
    color: '#1f6feb',
  },
  {
    id: 'savings-goal',
    name: 'Savings Goal Calculator',
    description: 'Track savings goals',
    category: 'finance',
    icon: Target,
    href: '/finance/savings-goal',
    color: '#1f6feb',
  },
  {
    id: 'emergency-fund',
    name: 'Emergency Fund Calculator',
    description: 'Calculate emergency fund needs',
    category: 'finance',
    icon: Home,
    href: '/finance/emergency-fund',
    color: '#1f6feb',
  },
  {
    id: 'lease-vs-buy',
    name: 'Lease vs Buy Calculator',
    description: 'Compare leasing vs buying',
    category: 'finance',
    icon: Home,
    href: '/finance/lease-vs-buy',
    color: '#1f6feb',
  },
  {
    id: 'inflation',
    name: 'Inflation Calculator',
    description: 'Calculate inflation impact',
    category: 'finance',
    icon: TrendingUp,
    href: '/finance/inflation',
    color: '#1f6feb',
  },
  {
    id: 'investment-return',
    name: 'Investment Return Calculator',
    description: 'Calculate investment returns',
    category: 'finance',
    icon: BarChart3,
    href: '/finance/investment-return',
    color: '#1f6feb',
  },

  // Health - 14 Calculators (all have pages)
  {
    id: 'bmi',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index',
    category: 'health',
    icon: Heart,
    href: '/health/bmi',
    color: '#238636',
  },
  {
    id: 'calorie-intake',
    name: 'Calorie Calculator',
    description: 'Estimate daily calorie needs',
    category: 'health',
    icon: Utensils,
    href: '/health/calories',
    color: '#238636',
  },
  {
    id: 'sleep-calculator',
    name: 'Sleep Calculator',
    description: 'Optimize your sleep schedule',
    category: 'health',
    icon: Moon,
    href: '/health/sleep',
    color: '#238636',
  },
  {
    id: 'macro-calculator',
    name: 'Macro Calculator',
    description: 'Calculate macronutrient ratios',
    category: 'health',
    icon: Activity,
    href: '/health/macro',
    color: '#238636',
  },
  {
    id: 'rep-max-calculator',
    name: 'One Rep Max',
    description: 'Calculate your 1RM strength',
    category: 'health',
    icon: Zap,
    href: '/health/rep-max',
    color: '#238636',
  },
  {
    id: 'water-intake',
    name: 'Water Intake Calculator',
    description: 'Calculate daily water needs',
    category: 'health',
    icon: Droplets,
    href: '/health/water-intake',
    color: '#238636',
  },
  {
    id: 'bmr-tdee',
    name: 'BMR & TDEE Calculator',
    description: 'Calculate metabolism & calories',
    category: 'health',
    icon: Zap,
    href: '/health/bmr-tdee',
    color: '#238636',
  },
  {
    id: 'body-fat',
    name: 'Body Fat Calculator',
    description: 'Calculate body fat percentage',
    category: 'health',
    icon: Activity,
    href: '/health/body-fat',
    color: '#238636',
  },
  {
    id: 'ideal-weight',
    name: 'Ideal Weight Calculator',
    description: 'Find your ideal weight range',
    category: 'health',
    icon: Target,
    href: '/health/ideal-weight',
    color: '#238636',
  },
  {
    id: 'tdee',
    name: 'TDEE Calculator',
    description: 'Calculate total daily energy expenditure',
    category: 'health',
    icon: Zap,
    href: '/health/tdee',
    color: '#238636',
  },
  {
    id: 'heart-rate',
    name: 'Heart Rate Calculator',
    description: 'Track training zones',
    category: 'health',
    icon: Heart,
    href: '/health/heart-rate',
    color: '#238636',
  },
  {
    id: 'calorie-burn',
    name: 'Calorie Burn Calculator',
    description: 'Estimate calories burned',
    category: 'health',
    icon: Activity,
    href: '/health/calorie-burn',
    color: '#238636',
  },
  {
    id: 'protein',
    name: 'Protein Calculator',
    description: 'Calculate daily protein needs',
    category: 'health',
    icon: Utensils,
    href: '/health/protein',
    color: '#238636',
  },

  // Math - 13 Calculators (all have pages)
  {
    id: 'percentage',
    name: 'Percentage Calculator',
    description: 'Calculate percentages quickly',
    category: 'math',
    icon: Percent,
    href: '/math/percentage',
    color: '#9e6a03',
  },
  {
    id: 'square-roots',
    name: 'Square Roots',
    description: 'Calculate square roots',
    category: 'math',
    icon: Square,
    href: '/math/roots',
    color: '#9e6a03',
  },
  {
    id: 'prime-checker',
    name: 'Prime Checker',
    description: 'Check if a number is prime',
    category: 'math',
    icon: Dice6,
    href: '/math/primes',
    color: '#9e6a03',
  },
  {
    id: 'logarithm',
    name: 'Logarithm',
    description: 'Calculate logarithms',
    category: 'math',
    icon: Infinity,
    href: '/math/logarithm',
    color: '#9e6a03',
  },
  {
    id: 'standard-deviation',
    name: 'Standard Deviation',
    description: 'Calculate statistical deviation',
    category: 'math',
    icon: Sigma,
    href: '/math/stddev',
    color: '#9e6a03',
  },
  {
    id: 'factorial',
    name: 'Factorial',
    description: 'Calculate factorials',
    category: 'math',
    icon: Calculator,
    href: '/math/factorial',
    color: '#9e6a03',
  },
  {
    id: 'quadratic',
    name: 'Quadratic Equation',
    description: 'Solve quadratic equations',
    category: 'math',
    icon: PlusSquare,
    href: '/math/quadratic',
    color: '#9e6a03',
  },
  {
    id: 'gcd-lcm',
    name: 'GCD & LCM Calculator',
    description: 'Find GCD and LCM',
    category: 'math',
    icon: PlusSquare,
    href: '/math/gcd-lcm',
    color: '#9e6a03',
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci Sequence',
    description: 'Generate Fibonacci sequences',
    category: 'math',
    icon: Sparkles,
    href: '/math/fibonacci',
    color: '#9e6a03',
  },
  {
    id: 'prime-factorization',
    name: 'Prime Factorization',
    description: 'Factor numbers into primes',
    category: 'math',
    icon: Layers,
    href: '/math/prime-factorization',
    color: '#9e6a03',
  },
  {
    id: 'geometry',
    name: 'Geometry Calculator',
    description: 'Calculate areas and volumes',
    category: 'math',
    icon: Box,
    href: '/math/geometry',
    color: '#9e6a03',
  },
  {
    id: 'combinations',
    name: 'Combinations & Permutations',
    description: 'Calculate odds',
    category: 'math',
    icon: Dice6,
    href: '/math/combinations',
    color: '#9e6a03',
  },
  {
    id: 'probability',
    name: 'Probability Calculator',
    description: 'Calculate probability',
    category: 'math',
    icon: Dice6,
    href: '/math/probability',
    color: '#9e6a03',
  },

  // Tools - 12 Calculators (all have pages)
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips and split bills',
    category: 'tools',
    icon: Coffee,
    href: '/tools/tip',
    color: '#0070f3',
  },
  {
    id: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate discounts and savings',
    category: 'tools',
    icon: Scissors,
    href: '/tools/discount',
    color: '#0070f3',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units',
    category: 'tools',
    icon: Globe,
    href: '/tools/convert',
    color: '#0070f3',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between currencies',
    category: 'tools',
    icon: Banknote,
    href: '/tools/currency',
    color: '#0070f3',
  },
  {
    id: 'fuel-cost',
    name: 'Fuel Cost Calculator',
    description: 'Calculate fuel costs',
    category: 'tools',
    icon: Fuel,
    href: '/tools/fuel',
    color: '#0070f3',
  },
  {
    id: 'gas-calculator',
    name: 'Gas Mileage Calculator',
    description: 'Calculate fuel efficiency',
    category: 'tools',
    icon: Fuel,
    href: '/tools/gas-calculator',
    color: '#0070f3',
  },
  {
    id: 'time-zone',
    name: 'Time Zone Converter',
    description: 'Convert between time zones',
    category: 'tools',
    icon: Globe,
    href: '/tools/time-zone',
    color: '#0070f3',
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Assess password security',
    category: 'tools',
    icon: Lock,
    href: '/tools/password-strength',
    color: '#0070f3',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert color formats',
    category: 'tools',
    icon: Palette,
    href: '/tools/color-converter',
    color: '#0070f3',
  },
  {
    id: 'temperature',
    name: 'Temperature Converter',
    description: 'Convert temperature scales',
    category: 'tools',
    icon: Zap,
    href: '/tools/temperature',
    color: '#0070f3',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and validate JSON',
    category: 'tools',
    icon: Type,
    href: '/tools/json-formatter',
    color: '#0070f3',
  },
]

export const CATEGORIES = {
  finance: { name: 'Finance', color: '#1f6feb', icon: '💰' },
  health: { name: 'Health', color: '#238636', icon: '❤️' },
  math: { name: 'Math', color: '#9e6a03', icon: '📐' },
  tools: { name: 'Tools', color: '#0070f3', icon: '🔧' },
}

export function getCalculatorsByCategory(category: Category) {
  return CALCULATORS.filter((calc) => calc.category === category)
}

export function getCalculator(id: string) {
  return CALCULATORS.find((calc) => calc.id === id)
}
